### ISSUE TITLE
[Feature]: Add new subject file from project Star

### ISSUE THREAD

**Issue by Haltarys** [Studio-17/Epitech-Subjects#22]
### Description

A friend of mine currently in first year at Epitech was tasked with solving a project I hadn't heard of called "Star". This project replaced the "FirTree" project from TEK1 C Pool.

### Expected behaviour

Add in the same directory as the FirTree [B-CPE-100_Star.pdf](https://github.com/Studio-17/Epitech-Subjects/files/13467904/B-CPE-100_Star.pdf) but keep the FirTree for posterity (obviously.)

**Comment by Clement-Fernandes** [comment]
Ok, thank you for your issue i'm gonna ad it.
