### ISSUE TITLE
[Feature]: Ajouter le projet My_Paint

### ISSUE THREAD

**Issue by Haltarys** [Studio-17/Epitech-Subjects#26]
### Description

Ajouter le nouveau projet [B-MUL-200_my_paint.pdf](https://github.com/Studio-17/Epitech-Subjects/files/14473124/B-MUL-200_my_paint.pdf) dans le dossier `Semestre-2/B-MUL-200`

### Expected behaviour

This should happened!

### Environment

- OS and version

**Comment by Clement-Fernandes** [comment]
Merci beaucoup !
