### ISSUE TITLE
[Feature]: Ajouter le projet Robot Factory

### ISSUE THREAD

**Issue by Haltarys** [Studio-17/Epitech-Subjects#27]
### Description

Ajouter le nouveau projet [B-CPE-200_RobotFactory.pdf](https://github.com/Studio-17/Epitech-Subjects/files/14473137/B-CPE-200_RobotFactory.pdf) dans le dossier `Semester-2/B-CPE-200`

### Expected behaviour

This should happened!

### Environment

- OS and version

**Comment by Haltarys** [comment]
Je vais aussi ajouter certains fichiers source censés être fournis avec le sujet.

**Comment by Clement-Fernandes** [comment]
Salut,

Merci pour les sujets, n'hésite pas à rajouter les fichiers dont tu parle et à envoyer plus de sujets si tu en a l'occasion. 😁

**Comment by Haltarys** [comment]
Hello, il me manque encore certains fichiers. Je ne les ai pas encore reçus, je les ajouterai tous quand je les aurai.
