### ISSUE TITLE
[Feature]: Ajouter le projet A-Maze-d

### ISSUE THREAD

**Issue by Haltarys** [Studio-17/Epitech-Subjects#29]
### Description

Ajouter le fichier [B-CPE-200_Amazed.pdf](https://github.com/Studio-17/Epitech-Subjects/files/14812324/B-CPE-200_Amazed.pdf) dans le dossier `Semester-2/B-CPE-200` 

Ajouter aussi le script [laby_gen.pl](https://github.com/Studio-17/Epitech-Subjects/files/14812325/laby_gen.txt). C'est un script Perl (avec l'extension `.pl`, pas `.txt`) qui génère des labyrinthes pour le développement du projet.

### Expected behaviour

This should happened!

### Environment

- OS and version

**Comment by Clement-Fernandes** [comment]
Done, merci pour tout !
