### ISSUE TITLE
Problèmes

### ISSUE THREAD

**Issue by Clement-Fernandes** [Studio-17/Epitech-Subjects#6]
**Salut**,

Si vous voyez quelconque problème sur le repo comme :
- un problème de README
- un sujet qui manque
- une idée pour améliorer le repo
Ou n'importe quel autre soucis, n'hésitez pas à répondre à cette **issue** et nous répondrons à vos attentes le plus rapidement possible.

**Comment by Quentin-Desmettre** [comment]
Bonjour,
Dans le semestre 4, module FUN, il semble manquer le sujet du imageCompressor
